# Generated by Django 4.1.6 on 2024-05-28 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry",
            old_name="entry",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="date",
        ),
        migrations.AddField(
            model_name="entry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="entry",
            name="title",
            field=models.CharField(default="Untitled", max_length=200),
            preserve_default=False,
        ),
    ]
