# Generated by Django 4.1.6 on 2024-05-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0003_alter_entry_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
