# Generated by Django 4.1.6 on 2024-05-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0005_supportmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportmessage",
            name="replied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="supportmessage",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supportmessage",
            name="reply",
            field=models.TextField(blank=True, null=True),
        ),
    ]
